name: EMGroup
description: Plugin de Permissao
main: net.eduard.permission.Main
version: 0.2
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
commands:
  groupmaster:
    aliases: [mg,group,user]
    usage: /<command> help
    description: Comando Principal do Plugin