name: Spawn
description: Sistema de Spawn configuravel
main: net.eduard.spawn.Main
version: 1.0
authors: [Eduard]
website: https://www.youtube.com/user/EduTutoriaisHD
depend: [EduardAPI]
commands:
  spawn:
    description: Teleportar para o Spawn
    permission: spawn.use
    usage: /<command>
  setspawn:
    usage: /<command>
    description: Setar o Spawn